# Generated by Django 4.1.5 on 2023-02-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktoreview',
            old_name='title',
            new_name='book_title',
        ),
        migrations.AddField(
            model_name='booktoreview',
            name='comment',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booktoreview',
            name='note',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booktoreview',
            name='review_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
