# Generated by Django 4.1.5 on 2023-02-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_tickettoreview_alter_ticketcreation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktoreview',
            name='note',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='tickettoreview',
            name='note',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=None, max_length=5),
        ),
    ]
