# Generated by Django 4.1.5 on 2023-02-13 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_customuser_following_customuser_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
